services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    ports:
      - "7777:8000"
    networks:
      - myNetwork
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    command:
      - celery --app=src.tasks.celery_app:celery_instance worker -l INFO
    env_file:
      - .env

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    command:
      - celery --app=src.tasks.celery_app:celery_instance beat -l INFO
    env_file:
      - .env

networks:
  myNetwork:
    external: true